// export const FETCH_CITYBIKES_BEGIN = 'FETCH_CITYBIKES_BEGIN';
// export const FETCH_CITYBIKES_SUCCESSS = 'FETCH_CITYBIKES_SUCCESSS';
// export const FETCH_CITYBIKES_FAILUIRE = 'FETCH_CITYBIKES_FAILUIRE';
